<div class="row">
    <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
            <?php echo $this->partial('cms/partial/form_header', ['title' => $title]);?>

            <?php echo $this->partial('cms/partial/message', ['msgInfo' => $msgInfo]);?>

            <div class="x_content">
                <br />
                <?php echo $this->form()->openTag($form);?>

                    <div class="item form-group">
                        <?php echo $this->formLabel($form->get('CategoryName')); ?>
                        <div class="col-md-6 col-sm-6 ">
                            <?php echo $this->formElement($form->get('CategoryName')); ?>
                            <?php echo $this->formElementErrors($form->get('CategoryName'), array('class' => 'error-message text-danger')); ?>
                        </div>
                    </div>

                    <div class="item form-group">
                        <?php echo $this->formLabel($form->get('CategoryParent')); ?>
                        <div class="col-md-6 col-sm-6 ">
                            <?php echo $this->formElement($form->get('CategoryParent')); ?>
                            <?php echo $this->formElementErrors($form->get('CategoryParent'), array('class' => 'error-message text-danger')); ?>
                        </div>
                    </div>

                    <div class="item form-group">
                        <?php echo $this->formLabel($form->get('CategoryStatus')); ?>
                        <div class="col-md-6 col-sm-6 ">
                            <?php echo $this->formElement($form->get('CategoryStatus')); ?>
                            <?php echo $this->formElementErrors($form->get('CategoryStatus'), array('class' => 'error-message text-danger')); ?>
                        </div>
                    </div>

                <?php echo $this->partial('cms/partial/form_button', ['form' => $form, 'backUrl' => $this->url('cms/category')]);?>

                <?php echo $this->form()->closeTag();?>
            </div>
        </div>
    </div>
</div>