<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="<?php echo $this->basePath();?>/cms_resource/images/favicon.ico" type="image/ico" />

    <title>Gentelella Alela! | </title>

    <!-- Bootstrap -->
    <link href="<?php echo $this->basePath();?>/cms_resource/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="<?php echo $this->basePath();?>/cms_resource/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="<?php echo $this->basePath();?>/cms_resource/vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- iCheck -->
    <link href="<?php echo $this->basePath();?>/cms_resource/vendors/iCheck/skins/flat/green.css" rel="stylesheet">

    <!-- bootstrap-progressbar -->
    <link href="<?php echo $this->basePath();?>/cms_resource/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
    <!-- JQVMap -->
    <link href="<?php echo $this->basePath();?>/cms_resource/vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet"/>
    <!-- bootstrap-daterangepicker -->
    <link href="<?php echo $this->basePath();?>/cms_resource/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="<?php echo $this->basePath();?>/cms_resource/build/css/custom.min.css" rel="stylesheet">

    <link href="<?php echo $this->basePath();?>/cms_resource/css/style.css" rel="stylesheet">
</head>

<body class="nav-md">
<div class="container body">
    <div class="main_container">
        <div class="col-md-3 left_col">
            <div class="left_col scroll-view">
                <div class="navbar nav_title" style="border: 0;">
                    <a href="<?php echo $this->url('cms');?>" class="site_title"><i class="fa fa-paw"></i> <span>CMS</span></a>
                </div>

                <div class="clearfix"></div>

                <!-- menu profile quick info -->
                <div class="profile clearfix">
                    <div class="profile_pic">
                        <img src="<?php echo $this->basePath();?>/cms_resource/images/img.jpg" alt="..." class="img-circle profile_img">
                    </div>
                    <div class="profile_info">
                        <span>Xin chào,</span>
                        <h2><?php echo $this->user->email;?></h2>
                    </div>
                </div>
                <!-- /menu profile quick info -->

                <br />

                <!-- sidebar menu -->
                <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                    <div class="menu_section">
                        <h3>General</h3>
                        <ul class="nav side-menu">
                            <li><a><i class="fa fa-home"></i>Nội dung <span class="fa fa-chevron-down"></span></a>
                                <ul class="nav child_menu">
                                    <li><a href="<?php echo $this->url('cms/category');?>">Danh mục</a></li>
                                    <li><a href="<?php echo $this->url('cms/article');?>">Bài viết</a></li>
                                    <li><a href="<?php echo $this->url('cms/page');?>">Trang nội dung</a></li>
                                </ul>
                            </li>
                            <li><a><i class="fa fa-home"></i>Website <span class="fa fa-chevron-down"></span></a>
                                <ul class="nav child_menu">
                                    <li><a href="<?php echo $this->url('cms/category');?>">Cấu hình chung </a></li>
                                    <li><a href="<?php echo $this->url('cms/category');?>">Menu </a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- /sidebar menu -->

                <!-- /menu footer buttons -->
                <div class="sidebar-footer hidden-small">
                    <a data-toggle="tooltip" data-placement="top" title="Logout" href="<?php echo $this->url('cms/logout');?>">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                    </a>
                </div>
                <!-- /menu footer buttons -->
            </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
            <div class="nav_menu">
                <div class="nav toggle">
                    <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                </div>
                <nav class="nav navbar-nav">
                    <ul class=" navbar-right">
                        <li class="nav-item dropdown open" style="padding-left: 15px;">
                            <a href="javascript:;" class="user-profile dropdown-toggle" aria-haspopup="true" id="navbarDropdown" data-toggle="dropdown" aria-expanded="false">
                                <img src="<?php echo $this->basePath();?>/cms_resource/images/img.jpg" alt=""><?php echo $this->user->email;?>
                            </a>
                            <div class="dropdown-menu dropdown-usermenu pull-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item"  href="<?php echo $this->url('cms/logout');?>"><i class="fa fa-sign-out pull-right"></i> Log Out</a>
                            </div>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
            <?= $this->content ?>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
            <div class="pull-right">
                CMS by <a href="https://colorlib.com">Zend Framework version 3</a>
            </div>
            <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
    </div>
</div>

<!-- jQuery -->
<script src="<?php echo $this->basePath();?>/cms_resource/vendors/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="<?php echo $this->basePath();?>/cms_resource/vendors/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<!-- FastClick -->
<script src="<?php echo $this->basePath();?>/cms_resource/vendors/fastclick/lib/fastclick.js"></script>
<!-- NProgress -->
<script src="<?php echo $this->basePath();?>/cms_resource/vendors/nprogress/nprogress.js"></script>
<!-- Chart.js -->
<script src="<?php echo $this->basePath();?>/cms_resource/vendors/Chart.js/dist/Chart.min.js"></script>
<!-- gauge.js -->
<script src="<?php echo $this->basePath();?>/cms_resource/vendors/gauge.js/dist/gauge.min.js"></script>
<!-- bootstrap-progressbar -->
<script src="<?php echo $this->basePath();?>/cms_resource/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
<!-- iCheck -->
<script src="<?php echo $this->basePath();?>/cms_resource/vendors/iCheck/icheck.min.js"></script>
<!-- Skycons -->
<script src="<?php echo $this->basePath();?>/cms_resource/vendors/skycons/skycons.js"></script>
<!-- Flot -->
<script src="<?php echo $this->basePath();?>/cms_resource/vendors/Flot/jquery.flot.js"></script>
<script src="<?php echo $this->basePath();?>/cms_resource/vendors/Flot/jquery.flot.pie.js"></script>
<script src="<?php echo $this->basePath();?>/cms_resource/vendors/Flot/jquery.flot.time.js"></script>
<script src="<?php echo $this->basePath();?>/cms_resource/vendors/Flot/jquery.flot.stack.js"></script>
<script src="<?php echo $this->basePath();?>/cms_resource/vendors/Flot/jquery.flot.resize.js"></script>
<!-- Flot plugins -->
<script src="<?php echo $this->basePath();?>/cms_resource/vendors/flot.orderbars/js/jquery.flot.orderBars.js"></script>
<script src="<?php echo $this->basePath();?>/cms_resource/vendors/flot-spline/js/jquery.flot.spline.min.js"></script>
<script src="<?php echo $this->basePath();?>/cms_resource/vendors/flot.curvedlines/curvedLines.js"></script>
<!-- DateJS -->
<script src="<?php echo $this->basePath();?>/cms_resource/vendors/DateJS/build/date.js"></script>
<!-- JQVMap -->
<script src="<?php echo $this->basePath();?>/cms_resource/vendors/jqvmap/dist/jquery.vmap.js"></script>
<script src="<?php echo $this->basePath();?>/cms_resource/vendors/jqvmap/dist/maps/jquery.vmap.world.js"></script>
<script src="<?php echo $this->basePath();?>/cms_resource/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js"></script>
<!-- bootstrap-daterangepicker -->
<script src="<?php echo $this->basePath();?>/cms_resource/vendors/moment/min/moment.min.js"></script>
<script src="<?php echo $this->basePath();?>/cms_resource/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>

<!-- Custom Theme Scripts -->
<script src="<?php echo $this->basePath();?>/cms_resource/build/js/custom.min.js"></script>

<?php echo $this->inlineScript() ?>

</body>
</html>
