<div class="ln_solid"></div>
<div class="item form-group">
    <div class="col-md-6 col-sm-6 offset-md-3">
        <button class="btn btn-secondary" type="button" onclick="location.href='<?php echo $backUrl;?>'">Thoát</button>
        <button class="btn btn-primary" type="reset">Làm lại</button>
        <?php
        echo $this->formHidden($form->get('csrf'));
        echo $this->formSubmit($form->get('SubmitBtn'));
        ?>
    </div>
</div>