<div class="login_wrapper">
    <div class="animate form login_form">
        <section class="login_content">
            <?php echo $this->form()->openTag($form);?>
                <h1>Đăng nhập</h1>
                <?php if ($error) {?>
                    <p class="text-danger"><?php echo $error;?></p>
                <?php }?>
                <div>
                    <?= $this->formElement($form->get('Email')); ?>
                    <?= $this->formElementErrors()->render($form->get('Email'), ['class' => 'help-block text-danger']) ?>
                </div>
                <div>
                    <?= $this->formElement($form->get('Password')); ?>
                    <?= $this->formElementErrors()->render($form->get('Password'), ['class' => 'help-block text-danger']) ?>
                </div>
                <div>
                    <?php
                    echo $this->formHidden($form->get('csrf'));
                    echo $this->formSubmit($form->get('LoginBtn'));
                    ?>
                </div>
                <div class="clearfix"></div>
            <?php echo $this->form()->closeTag();?>
        </section>
    </div>
</div>